apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-depl
  labels:
    app: accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      name: accounts-depl
      labels:
        app: accounts
    spec:
      containers:
        - name: accounts-depl
          image: gohil90/spring-boot-docker-k8s:v0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
      